apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-app
  namespace: demo-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sleep", "3600"]
